### ISSUE TITLE
models\vanilla_cnn\create_model()\model.fit() not working

### ISSUE THREAD

**Issue by UrosOgrizovic** [UrosOgrizovic/SimpleGoogleQuickdraw#1]
Here's the full traceback:
```
Traceback (most recent call last):
  File "C:/Users/grizl/OneDrive/Desktop/FTN/SK/projekat/SimpleGoogleQuickdraw/models/vanilla_cnn.py", line 126, in <module>
    create_model(x_tr, y_tr, x_val, y_val, x_tst, y_tst)
  File "C:/Users/grizl/OneDrive/Desktop/FTN/SK/projekat/SimpleGoogleQuickdraw/models/vanilla_cnn.py", line 50, in create_model
    validation_data=(x_validation, y_validation))
  File "C:\Users\grizl\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 1239, in fit
    validation_freq=validation_freq)
  File "C:\Users\grizl\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training_arrays.py", line 196, in fit_loop
    outs = fit_function(ins_batch)
  File "C:\Users\grizl\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3734, in __call__
    value = ops.convert_to_tensor(value, dtype=tensor.dtype)
  File "C:\Users\grizl\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1184, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "C:\Users\grizl\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1242, in convert_to_tensor_v2
    as_ref=False)
  File "C:\Users\grizl\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1296, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\grizl\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\framework\tensor_conversion_registry.py", line 52, in _default_conversion_function
    return constant_op.constant(value, dtype, name=name)
  File "C:\Users\grizl\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 227, in constant
    allow_broadcast=True)
  File "C:\Users\grizl\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 235, in _constant_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "C:\Users\grizl\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 96, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: setting an array element with a sequence.
```
`x_train`, `x_validation`, `x_test`, `y_train`, `y_validation`, `y_test` are all of type `numpy.ndarray`
Shapes:
`x_train` - (240, 28, 28, 1)
`x_validation` - (80, 28, 28, 1)
`x_test` - (80, 28, 28, 1)
`y_train` - before one-hot encoding: (240, ); after one-hot encoding: (240, 4)
`y_validation` - before one-hot encoding: (80, ); after one-hot encoding: (80, 4)
`y_test` - before one-hot encoding: (80, ); after one-hot encoding: (80, 4)

**Comment by UrosOgrizovic** [comment]
(resolve #2)
